services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_appBackend
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-cteb561u0jms7399bj7g-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_DATABASE=bd_pgsql_backend_laravel
      - DB_USERNAME=bd_pgsql_backend_laravel_user
      - DB_PASSWORD=cYA3olBZoXuWQzMO0R8tTeG3qAUopGyu
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel_dbBackend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tierrita24
      POSTGRES_DB: vamos
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webserverBackend
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: